### ISSUE TITLE
Invalid tags in plugin.json

### ISSUE THREAD

**Issue by cschol** [ed9m/ed9m_vcv#1]
During plugin integration in the Rack library the validation script has found the following issues:

```
[ed9m_vcv] Validating plugin.json...FAILED
[ed9m_vcv] Issues found in `plugin.json`:

AbletonPush2: invalid module tags: pattern, mapping
-- Valid tags are defined in https://raw.githubusercontent.com/VCVRack/Rack/v1/src/tag.cpp
```

**Comment by xnamahx** [comment]
Hi @ed9m 
Added some changes for this on my [repo](https://github.com/xnamahx/PushMapVCV). 

Thanks for sharing
